// Generated by CoffeeScript 1.6.3
var americano, initMailboxes, port, setupRealtime;

americano = require('americano');

initMailboxes = require('./server/initializers/mailbox');

setupRealtime = require('./server/initializers/realtimer');

process.on('uncaughtException', function(err) {
  console.error(err);
  return console.error(err.stack);
});

port = process.env.PORT || 9282;

americano.start({
  name: 'Cozy Mails',
  port: port
}, function(app, server) {
  app.server = server;
  setupRealtime(app);
  if (process.env.NODE_ENV !== "test") {
    return initMailboxes();
  }
});
