// Generated by CoffeeScript 1.6.3
var Mailbox;

Mailbox = require('../models/mailbox');

module.exports = function() {
  var importBox;
  importBox = function(box) {
    return box.fullImport();
  };
  return Mailbox.all(function(err, boxes) {
    var box, _i, _len, _ref, _results,
      _this = this;
    if (err) {
      console.log(err);
      return console.log("Something went wrong while checking mailboxes");
    } else {
      _results = [];
      for (_i = 0, _len = boxes.length; _i < _len; _i++) {
        box = boxes[_i];
        if (box.status === "import_preparing") {
          box.log("start again import from scracth");
          _results.push(box.reset(function(err) {
            if (err) {
              return box.log(err);
            } else {
              return importBox(box);
            }
          }));
        } else if ((_ref = box.status) === "import_failed" || _ref === "importing" || _ref === "freezed") {
          _results.push(box.reset(function(err) {
            if (err) {
              return box.log(err);
            } else {
              return importBox(box);
            }
          }));
        } else {
          box.log("status " + box.status);
          _results.push(box.log("already imported"));
        }
      }
      return _results;
    }
  });
};
