// Generated by CoffeeScript 1.6.3
var MailSent, americano;

americano = require('americano-cozy');

module.exports = MailSent = americano.getModel('MailSent', {
  createdAt: {
    type: Number,
    "default": 0
  },
  sentAt: {
    type: Number,
    "default": 0
  },
  subject: String,
  from: String,
  to: String,
  cc: String,
  bcc: String,
  html: String
});

MailSent.date = function(params, callback) {
  return MailSent.request("date", params, callback);
};

MailSent.dateId = function(params, callback) {
  return MailSent.request("dateId", params, callback);
};
