// Generated by CoffeeScript 1.6.3
var americano, byEmailRequest, byMailboxRequest, byTypeRequest, dateIdRequest, dateMailboxRequest, dateRequest, folderDateRequest, mailboxRequest;

americano = require('americano-cozy');

mailboxRequest = function() {
  return emit(doc.mailbox, doc);
};

dateIdRequest = function() {
  return emit([doc.dateValueOf, doc._id], doc);
};

dateRequest = function() {
  return emit(doc.dateValueOf, doc);
};

dateMailboxRequest = function() {
  return emit([doc.mailbox, doc.dateValueOf], doc);
};

folderDateRequest = function() {
  return emit([doc.folder, doc.dateValueOf], doc);
};

byEmailRequest = function() {
  return emit(doc.login, doc);
};

byMailboxRequest = function() {
  return emit(doc.mailbox, doc);
};

byTypeRequest = function() {
  return emit(doc.specialType, doc);
};

module.exports = {
  email: {
    all: americano.defaultRequests.all,
    date: dateRequest,
    dateId: dateIdRequest,
    byMailbox: mailboxRequest,
    dateByMailbox: dateMailboxRequest,
    folderDate: folderDateRequest
  },
  mailbox: {
    all: americano.defaultRequests.all,
    byEmail: byEmailRequest
  },
  mailfolder: {
    all: americano.defaultRequests.all,
    byMailbox: byMailboxRequest,
    byType: byTypeRequest
  }
};
