// Generated by CoffeeScript 1.6.3
var MailFolder;

MailFolder = require('../models/mailfolder');

module.exports = {
  getFolder: function(req, res, next, id) {
    var _this = this;
    return MailFolder.find(id, function(err, folder) {
      if (err) {
        return next(err);
      } else if (!folder) {
        return res.send({
          error: 'not found'
        }, 404);
      } else {
        req.folder = folder;
        return next();
      }
    });
  },
  index: function(req, res, next) {
    return MailFolder.all(function(err, folders) {
      if (err) {
        return next(err);
      } else {
        return res.send(folders || []);
      }
    });
  },
  show: function(req, res, next) {
    return res.send(req.folder);
  }
};
