// Generated by CoffeeScript 1.6.3
var MailSender, nodemailer;

nodemailer = require("nodemailer");

MailSender = (function() {
  function MailSender(mailbox) {
    this.mailbox = mailbox;
  }

  MailSender.prototype.sendMail = function(data, callback) {
    var message, transport;
    transport = nodemailer.createTransport("SMTP", {
      secureConnection: this.mailbox.smtpSsl,
      host: this.mailbox.smtpServer,
      port: this.mailbox.smtpPort,
      auth: {
        user: this.mailbox.login,
        pass: this.password
      }
    });
    message = {
      from: this.mailbox.smtpSendAs,
      to: data.to,
      cc: data.cc != null ? data.cc : void 0,
      bcc: data.bcc != null ? data.bcc : void 0,
      subject: data.subject,
      headers: data.headers != null ? data.headers : void 0,
      html: data.html,
      generateTextFromHTML: true
    };
    transport.sendMail(message, callback);
    return transport.close();
  };

  return MailSender;

})();

module.exports = MailSender;
